%% This script loads spike-time data generated by Yubo model and plots raster plot

clear all

%% Load data

filename = 'gc_O1.dat';

[data t cellname ntp nc] = Load_NEURON_Data(gc_O1.dat);
% data     - numeric data matrix
% t        - time vector
% cellname - name of cell type
% ntp      - # of time points
% nc       - # of cells

% surface plot looks cool (for fun)
% surf(data)
% shading interp
% colormap hot


%% Generate raster plot

th = 10; % threshold for detecting spike (mV)
color = [0,0,0];
fs = 14; % fontsize

[spktimes figH] = Plot_NEURON_Raster(data,t,th,cellname,color,fs);



