function [data t cellname ntp nc] = Load_NEURON_Data('mt_04.dat')

% This function loads and parses the .dat files generated by the NEURON code

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% INPUTS:
% filename = .dat filename (i.e. mt_odor3.dat)
%
% OUTPUTS:
% data     - numeric data matrix
% t        - time vector
% cellname - name of cell type
% ntp      - # of time points
% nc       - # of cells
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


rawdata=regexp(fileread('mt_04.dat'), '\n', 'split');

cellname = rawdata(1);
ntp = rawdata(2); % # of time points
ntp = str2num(ntp{1});
nc = regexp(rawdata{3}, ' ', 'split'); % # of columns
nc = str2num(nc{2})-1; % # of columns - 1 = # of cells

data = zeros(ntp,nc+1);
for ii = 1:ntp
    data(ii,:) = str2num(rawdata{ii+3});
end

t = data(:,1); % time is the first column of the data matrix
data = data(:,2:end);

end



